#cloud-config
datasource:
  Ec2:
    strict_id: false
ssh_pwauth: no
users:
  - name: vadim
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDTL8AWHVid601egSVjV48/+nZcYeI+qHtF23jl0v/7CVNGnTFaz51pppdmPSLR43/F1f8rhl5od5mbLTYktY5X29XOzNTnroezdQgXoaSkmFh9o0ArN4iBS7A2rlcK0uKVf8JVpdFp8Tk3D8NY3PEazbm2RDI5we7JlGaFDBVL4qWV88pohK8pzDCar2E2S1FVbpXblUrqSd9vawiVVD0Zf7ANyM733663rkMSkt6+42KYuUz1mKtFYT7DyHHJPXyeyj0CUhMUTfrczhdKuEChIaGRZjVIFoF0mIDbkspl9aunTvcMShmr2dVFsguzBsa0jBrC+Djsdy7IRfS2cx5fbII3SfpfBOEkdzbmaIkMcxHRhhHbV+0hjfhbZ+FSms0QAoPoaYTyLzZOzoveVAXFVdTXUyZOn4X/7LWbUqhs/QLzb2FIo8jM6x6e2S5G3KJuow4wUrYFNplGX2r9T7NHTQHHJW7ibgKR9QEPBbso2Bs3i8r7HjJnB0ULJkBW+8M= vboxuser@VADIM
runcmd: []
