ssh_pwauth: no
users:
  - name: vadim
    groups: sudo
    shell: /bin/bash
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDe3rF4LrC5zxVugBk1HRTbuu6PfCapg7kfPXXAwV9RR3+T5pIfzsnelfglN63mJgY5HjT/el3yD9G1jAMwbIAgcr9xrLE7x5CmEoUtcWuP9TVTh7gkyk26Y4gMCdzEtvk+Ihiis0oIVBeWrQMdTDY4i3pVaSUIQ9x2cJrYgNsmst2LKdHAPkyxSgT2hNhSOBaXV1KVpuj+bMI47+rJ+f4dWhnvndPK3nDLn2ynTJoIO0AAhoWPNZ+zukJ3AQIJq9scq5Jcla7/7tUgvx7BtB3UaFM9ToRrXpqYltw5fiKOnII8u9GUlE+xzHrTj9GEN6Uly2aifJnVyvhWUoL6d6hMay7QOsni/PO7+Erf3BeTTZoHDr5+i8ShU+/50k2E/b2HoAL68KS99LYe9aQSEvB8xOT+91I2Oa+8Gpg4NthPUKC4PUGFkCERmcXkZH41NEyNZoTFtW6vs0ShBBdTc/0/FPdgFDSTiXI8tPxhHrwVzJsQ5v90GaHN+DwX7UlloXk=
