#cloud-config
datasource:
  Ec2:
    strict_id: false
ssh_pwauth: no
users:
  - name: vadim
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCoy2dufSJ4Ulk2xCxuzOzhIlVv2CGXKHOQm1bEMsTnAUXfDtASyjNGEKn1ivwRVpBBqqWGpqJ95v9gyj0VxrVPegJaRRQ2OqU7KvFfnMrfKqBdrsq2BNou1QeOkORXSj7CvjOlyvg/ltucowln6SDGSLz1gvA809lif3IFVjT00FbNLT/fm2oU0Zh0gVHJZ4HEgGXVnJy9ghrq9V2UktqJEqW4h86/Dh72P/VPLCISCrGzvzbWnllDzl6o4OYeRB7cWEN/ma7cEDBOsOJeGtRl+ZhWbFnnYCRzgb30TsdNy50OglLyzN8AyZ2HcELEUahPTy1yRtmHKbwx/QqUJvFK6nm+kfznA9hfOFeEQuGq7ob/WnXqmfYLpbLJx5Ht6dhj6Wo91SVcZtQnd82rzb7MLyg1LKuuolNY8+wIsFFeUi/kPk7wQAZAXQ1I7Ek7YfxqBgtuNh1Lzs8biio8R+47FcmcGBtT+Rd7OloFNrjk/zvoMgNimvNEiG+N9OAHP5c=
runcmd: []