version: "3"
services:
  nginx-proxy:
    image: nginx:1.25.1-alpine
    container_name: nginx_proxy
    restart: unless-stopped
    volumes:
      - ./conf.d/:/etc/nginx/conf.d/
  ports:
    - "80:80"
    - "443:443"
  networks:
    - net
